Background editor
on21viktoria/trvl-card pull request #16
Opened 2022-05-06 12:47 UTC by on21viktoria

added functionalities to select picture and background color for postcard

2022-05-06 15:08 UTC, ON21MB commented on src/components/Editor/Sidebar/Background.vue
>  }
There are two closing </style>-tags.

2022-05-06 15:12 UTC, ON21MB commented on src/components/Editor/Sidebar/Sticker.vue
>      <!-- <p class="tool-title subtitle">Suche</p>
Do we still need this code which is toggled?

2022-05-06 15:17 UTC, ON21MB commented on src/components/Editor/PostcardLayout.vue
> +import { mapGetters, mapState } from "vuex";
This import doesn't work in my VS.

2022-05-06 15:24 UTC, ON21MB commented on src/components/Editor/Sidebar/Photos.vue
> +      this.$store.dispatch("setPicture", picture);
This method doesn't work in my VS, it has problems with the .$store part.

2022-05-06 15:24 UTC, ON21MB commented on src/components/Editor/Sidebar/Sticker.vue
> +      this.$store.dispatch("setSticker", sticker)
Same here, the method doesn't work.

2022-05-06 15:25 UTC, ON21MB commented on src/store/pictures.ts
> +      state.currentPicture = payload;
In my VS, there are problems with the type of state.

2022-05-06 15:27 UTC, ON21MB requested changes
I think there are a few things that need to be checked before merging the branch. I can't load the page so far! I'll review it once again after the changes!

2022-05-06 16:46 UTC, on21viktoria commented on src/components/Editor/Sidebar/Background.vue
> +      this.$store.dispatch("setBackgroundColor", colorselector.value);
einmal npm install machen

2022-05-08 07:08 UTC, ON21MB commented
**I tried the branch again after running npm install. I could visit the page!**

- The color picker for the background works fine. 
- It's just a bit confusing because there's written "you can choose from either a background picture or a color" but actually in this section of the toolbar you can only choose the color - the photos are in Robin's "photo"-part of the sidebar, aren't they? I'd consider calling the section "background-color" and is it maybe possible to resize the color-preview-box? Because for now it looks a bit "broken", from a user's point of view it's not really clear to me that I have to click on the small white box to change the background-color.
- Also applying the stickers to the postcard works well. 
- the this.$store.dispatch()-method is still underlined in red in my VS, but I'm not sure if this is just a problem of VS, since it works. 
- If we pay attention that all other comments have been resolved, for me we can merge the branch!

2022-05-12 08:01 UTC, merged